### ISSUE TITLE
Stretch: Live Tracking a Carbie

### ISSUE THREAD

**Issue by acamacho4957** [co2-u/carbies#31]
- [x] research 
 - [x] GPS Permissions
- [x] add button in RouteFragment -> go to LiveTrackFragment
- [x] create LiveTrackFragment with a mapview that shows user's path
- [x] start and stop buttons
- [x] start button starts tracking path
- [x] stop button saves route and creates carbie
